{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionDidFinishEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBackgroundURLSession"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsessiondidfinishevents(forbackgroundurlsession:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsessiondidfinishevents(forbackgroundurlsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSessionDidFinishEvents(forBackgroundURLSession:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"URLSessionDelegate.urlSessionDidFinishEvents(forBackgroundURLSession:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionDidFinishEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBackgroundURLSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":")"}],"title":"urlSessionDidFinishEvents(forBackgroundURLSession:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore(im)URLSessionDidFinishEventsForBackgroundURLSession:","modules":[{"name":"OpenpathMobile"}],"navigatorTitle":[{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"]]},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"role":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"abstract":[{"type":"text","text":"The entry point for all functionality in the OpenpathMobile SDK."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/urlSessionDidFinishEvents(forBackgroundURLSession:)":{"role":"symbol","title":"urlSessionDidFinishEvents(forBackgroundURLSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionDidFinishEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBackgroundURLSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSessionDidFinishEvents(forBackgroundURLSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsessiondidfinishevents(forbackgroundurlsession:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","title":"OpenpathMobile","abstract":[{"type":"text","text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"URLSessionDidFinishEventsForBackgroundURLSession:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/title","value":"URLSessionDidFinishEventsForBackgroundURLSession:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}