{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Most functions send their responses by calling functions in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"},{"type":"text","text":"."}]}],"type":"aside","name":"Note"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Always access "},{"type":"codeVoice","code":"OpenpathMobileAccessCore.shared"},{"type":"text","text":" on the main thread"}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscore"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)NSURLSessionDelegate","doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)NSObject","doc:\/\/org.cocoapods.OpenpathMobile\/s7CVarArgP","doc:\/\/org.cocoapods.OpenpathMobile\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.OpenpathMobile\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.OpenpathMobile\/SQ","doc:\/\/org.cocoapods.OpenpathMobile\/SH","doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)UNUserNotificationCenterDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The entry point for all functionality in the OpenpathMobile SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"title":"OpenpathMobileAccessCore","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","modules":[{"name":"OpenpathMobile"}],"navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/enableErrorNotificationsForItem(enabled:itemType:itemId:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getAuthorizationStatuses()","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getErrors()","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getReadersInRange(rssiThreshold:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getSdkVersion()","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getUserApiToken(userOpal:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/provision(setupMobileToken:callback:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/refreshItemState(itemType:itemId:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/refreshUserSettings()","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/requestAuthorization(_:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/sendFeedback(subject:message:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/setLogLevel(logLevel:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/softRefresh()","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/switchUser(userOpal:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/syncUser()","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/unlock(itemType:itemId:requestId:timeout:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/unprovision(userOpal:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didBecomeInvalidWithError:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didReceive:completionHandler:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSessionDidFinishEvents(forBackgroundURLSession:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/shared"]}],"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/urlSession(_:didReceive:completionHandler:)":{"role":"symbol","title":"urlSession(_:didReceive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didReceive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsession(_:didreceive:completionhandler:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/getReadersInRange(rssiThreshold:)":{"role":"symbol","title":"getReadersInRange(rssiThreshold:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReadersInRange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rssiThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getReadersInRange(rssiThreshold:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/getreadersinrange(rssithreshold:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/provision(setupMobileToken:callback:)":{"role":"symbol","title":"provision(setupMobileToken:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provision"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupMobileToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ProvisionResult","preciseIdentifier":"s:14OpenpathMobile15ProvisionResultV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"TitaniumError","preciseIdentifier":"s:14OpenpathMobile13TitaniumErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Provision a user."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/provision(setupMobileToken:callback:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/provision(setupmobiletoken:callback:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"role":"symbol","title":"OpenpathMobileAccessCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/getSdkVersion()":{"role":"symbol","title":"getSdkVersion()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSdkVersion"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getSdkVersion()","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/getsdkversion()"},"doc://org.cocoapods.OpenpathMobile/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/SQ"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/getAuthorizationStatuses()":{"role":"symbol","title":"getAuthorizationStatuses()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAuthorizationStatuses"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getAuthorizationStatuses()","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/getauthorizationstatuses()"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/switchUser(userOpal:)":{"role":"symbol","title":"switchUser(userOpal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userOpal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Stops services of the current user if it is different from the required one, then loads the info of the required user from the stored records and restarts Openpath services for the new user."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/switchUser(userOpal:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/switchuser(useropal:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/enableErrorNotificationsForItem(enabled:itemType:itemId:)":{"role":"symbol","title":"enableErrorNotificationsForItem(enabled:itemType:itemId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableErrorNotificationsForItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables or disables error notifications for an item (reader or entry)."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/enableErrorNotificationsForItem(enabled:itemType:itemId:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/enableerrornotificationsforitem(enabled:itemtype:itemid:)"},"doc://org.cocoapods.OpenpathMobile/objc(pl)UNUserNotificationCenterDelegate":{"type":"unresolvable","title":"UNUserNotificationCenterDelegate","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)UNUserNotificationCenterDelegate"},"doc://org.cocoapods.OpenpathMobile/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCoreDelegate","preciseIdentifier":"s:14OpenpathMobile0aB18AccessCoreDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Create and assign your delegate here"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/delegate"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/urlSessionDidFinishEvents(forBackgroundURLSession:)":{"role":"symbol","title":"urlSessionDidFinishEvents(forBackgroundURLSession:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionDidFinishEvents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBackgroundURLSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSessionDidFinishEvents(forBackgroundURLSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsessiondidfinishevents(forbackgroundurlsession:)"},"doc://org.cocoapods.OpenpathMobile/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/s7CVarArgP"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/unlock(itemType:itemId:requestId:timeout:)":{"role":"symbol","title":"unlock(itemType:itemId:requestId:timeout:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unlocks an entry or reader."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/unlock(itemType:itemId:requestId:timeout:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/unlock(itemtype:itemid:requestid:timeout:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/syncUser()":{"role":"symbol","title":"syncUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncUser"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Synchronizes data for the currently active user."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/syncUser()","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/syncuser()"},"doc://org.cocoapods.OpenpathMobile/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)NSObject"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/refreshUserSettings()":{"role":"symbol","title":"refreshUserSettings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshUserSettings"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Request a refresh of user data (cloud keys, whether user has remote or override unlock, etc.) from the cloud."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/refreshUserSettings()","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/refreshusersettings()"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/getUserApiToken(userOpal:)":{"role":"symbol","title":"getUserApiToken(userOpal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserApiToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userOpal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns the user’s Openpath REST API Token."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getUserApiToken(userOpal:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/getuserapitoken(useropal:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","title":"OpenpathMobile","abstract":[{"type":"text","text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile"},"doc://org.cocoapods.OpenpathMobile/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/objc(cs)NSObject"},"doc://org.cocoapods.OpenpathMobile/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/s23CustomStringConvertibleP"},"doc://org.cocoapods.OpenpathMobile/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/SH"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/unprovision(userOpal:)":{"role":"symbol","title":"unprovision(userOpal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unprovision"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userOpal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Clears the Openpath user data for the requested user."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/unprovision(userOpal:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/unprovision(useropal:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"role":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"abstract":[{"type":"text","text":"The entry point for all functionality in the OpenpathMobile SDK."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/softRefresh()":{"role":"symbol","title":"softRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"softRefresh"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Request a refresh of controller configurations (e.g., entry and reader settings) and user entry permissions from the cloud."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/softRefresh()","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/softrefresh()"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/sendFeedback(subject:message:)":{"role":"symbol","title":"sendFeedback(subject:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFeedback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"subject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sends feedback and SDK logs via email to Openpath."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/sendFeedback(subject:message:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/sendfeedback(subject:message:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/urlSession(_:didBecomeInvalidWithError:)":{"role":"symbol","title":"urlSession(_:didBecomeInvalidWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didBecomeInvalidWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didBecomeInvalidWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSession:didBecomeInvalidWithError:"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsession(_:didbecomeinvalidwitherror:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/setLogLevel(logLevel:)":{"role":"symbol","title":"setLogLevel(logLevel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Set the log level for Openpath logs."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/setLogLevel(logLevel:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/setloglevel(loglevel:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"}],"abstract":[{"type":"text","text":"The single instance of this class"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/shared","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/shared"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/getErrors()":{"role":"symbol","title":"getErrors()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getErrors"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/getErrors()","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/geterrors()"},"doc://org.cocoapods.OpenpathMobile/objc(pl)NSURLSessionDelegate":{"type":"unresolvable","title":"NSURLSessionDelegate","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)NSURLSessionDelegate"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/refreshItemState(itemType:itemId:)":{"role":"symbol","title":"refreshItemState(itemType:itemId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshItemState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Request the updated state for an item."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/refreshItemState(itemType:itemId:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/refreshitemstate(itemtype:itemid:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/requestAuthorization(_:)":{"role":"symbol","title":"requestAuthorization(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthorization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Requests permission for systems services."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/requestAuthorization(_:)","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/requestauthorization(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didBecomeInvalidWithError:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didReceive:completionHandler:)","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSessionDidFinishEvents(forBackgroundURLSession:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)NSURLSessionDelegate","doc:\/\/org.cocoapods.OpenpathMobile\/objc(pl)UNUserNotificationCenterDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCore"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSession(_:didReceive:completionHandler:)\/title","value":"URLSession:didReceiveChallenge:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSession(_:didReceive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/title","value":"URLSessionDidFinishEventsForBackgroundURLSession:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSession(_:didBecomeInvalidWithError:)\/title","value":"URLSession:didBecomeInvalidWithError:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSession(_:didBecomeInvalidWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:didBecomeInvalidWithError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}